---
title: Tedy Herlambang/sistemekonomi
output:
  xaringan::moon_reader:
    chakra: libs/remark-latest.min.js  
    # self_contained: TRUE
    includes:
      in_header: conf/style-header.html
    lib_dir: libs
    seal: false
    css: ["default", "conf/css/style.css", "conf/css/fonts.css"]
    nature:
      beforeInit: ["conf/js/gifffer.min.js", "conf/js/style-macros.js"]
      ratio: 16:9
---

```{r setup, echo = F}
knitr::opts_chunk$set(
  comment = "#",
  #cache = TRUE,
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 7,
  fig.height = 5.25,
  fig.align = 'center',
  fig.retina = 3
)

# base plot layout
mypar = list(mar = c(3,3,0.5,0.5), mgp = c(1.5, 0.3, 0), tck = -.008)

# xaringan Extra
xaringanExtra::use_xaringan_extra(c("tile_view", "animate_css", "tachyons"))
xaringanExtra::use_extra_styles(
  hover_code_line = TRUE,         #<<
  mute_unhighlighted_code = TRUE  #<<
)
xaringanExtra::use_editable(expires = 1)
xaringanExtra::use_panelset()
xaringanExtra::use_scribble()
```
class: middle, title-slide

<!-- top logo (comment to remove or edit on `conf/css/style.css:23`) -->
<div class="lab-logo"></div>
<!-- <div class="uni-logo"></div> -->

# Sistem Ekonomi Indonesia

<hr width="100%" align="left" size="0.3" color="red"></hr>

## <span style="color:red">Sistem Ekonomi Sesi 8</span>

### Tedy Herlambang .small[<br>]

<br><br><br><br><br>
[<i class="fas fa-blog" style="color:#e7e8e2"></i> bangtedy.github.io](https://bangtedy.github.io)

[<i class="fa fa-twitter fa-lg" style="color:#e7e8e2"></i> @t_hlb](https://twitter.com/t_hlb)

---

# Pengantar

- Capaian Pembelajaran Umum:

Mahasiswa mampu menjelaskan perlunya dilakukan reformasi system ekonomi Indonesia menuju system ekonomi Pancasila melalui implementasi agenda-agenda ekonomi kerakyatan di Indonesia.

- Capaian Pembelajaran Khusus, mahasiswa diharapkan dapat :

  1.	Menganalisis dan menjelaskan perlunya melakukan reformasi sosial melalui reformasi system ekonomi Indonesia
  2.	menjelaskan landasan constitutional dan filosofis, prinsip dan ciri-ciri penerapan system ekonomi Pancasila
  3.	menjelaskan implementasi agenda ekonomi kerakyatan melalui peranan koperasi, jaminan sosial, dan lembaga keuangan mikro di Indonesia


---


class: middle, center, inverse

# KB2: SISTEM EKONOMI PANCASILA
<hr width="100%" align="left" size="0.3" color="#9bb80d"></hr>

---

# Landasan Ekonomi Pancasila

- Seminar Nasional di UGM 1980
  - Ekonomi Pancasila bukan hanya sebagai sebuah sistem ekonomi, tetapi sebagai sebuah ilmu ekonomi alternatif.
- Gagasan Sistem Ekonomi Pancasila (SEP) terus melemah karena tidak didukung oleh Orde Baru yang ditopang teknokrat Neo-Liberal
- SEP digali atas dasar:
  - SE terkait dengan ideologi, sistem nilai dan sosial budaya dimana sistem itu dikembangkan
  - Bangsa Indonesia beragam suku, budaya, agama, dan bahasa
  - Kondisi sosek: golongan sejahtera dan miskin, pendidikan tinggi dan rendah, industri besar dan kecil
- EP berpijak pada gagasan normatif dan fakta-fakta empirik


---

# Prinsip dan Platform Sistem Ekonomi Pancasila

- Ekonomika Etik
- Ekonomika Humanistik
- Nasionalisme Ekonomi
- Demokrasi Ekonomi
- Ekonomi Berkeadilan Sosial
---

# Demokratisasi Modal Institusional Melalui Koperasi

### UU No. 25/1992
1. Keanggotaan bersifat suka rela dan terbuka
2. Pengelolaan dilakukan secara demokratis
3. Pembagian sisa hasil usaha dilakukan dengan adil
4. Pemberian balas jasa yang terbatas pada modal
5. Kemandirian

---

# Demokratisasi Modal Material Melalui Kredit Rakyat

- Masalah pengembangan kredit rakyat
- Pengembangan lembaga keuangan mikro

---
class: inverse, right, bottom

# Matur nuwun, find me at...
<hr width="45%" align="right" size="0.3" color="orange"></hr>

[<i class="fa fa-twitter fa-lg" style="color:#e7e8e2"></i> <span style="color:#fc911e"> @t_hlb </span>](https://twitter.com/t_hlb)

[<i class="fas fa-blog" style="color:#fc911e"></i><span style="color:#e7e8e2"> bangtedy.github.io</span>](https://bangtedy.github.io)
